import { DataTypes, Model } from 'sequelize';

export default function initMockTrialModel(sequelize) {
    class MockTrial extends Model {}

    MockTrial.init(
        {
            id: {
                type: DataTypes.INTEGER,
                autoIncrement: true,
                primaryKey: true,
            },
            caseData: {
                type: DataTypes.JSONB,
                allowNull: false,
                comment: 'Stores the case description, role, country, state, etc.',
            },
            caseAnalysis: {
                type: DataTypes.TEXT,
                allowNull: true,
                comment: 'Stores the analysis generated by OpenAI or other services.',
            },
            summary: {
                type: DataTypes.TEXT,
                allowNull: true,
                comment: 'Stores a summary of the case or analysis.',
            },
            filesUrl: {
                type: DataTypes.ARRAY(DataTypes.STRING),
                allowNull: true,
                comment: 'Stores URLs of uploaded files.',
            },
            userId: {
                type: DataTypes.INTEGER,
                allowNull: false,
                references: {
                    model: 'users',
                    key: 'id',
                },
            },
        },
        {
            sequelize,
            modelName: 'MockTrial',
            tableName: 'mockTrials',
            paranoid: true, // Enable soft deletes
        }
    );


    return MockTrial;
}
